spring.application.name=product-service

server.port=8082

# Set Your Context Path Here
server.servlet.context-path=/product-service

spring.datasource.url=jdbc:mysql://localhost:3306/product_db
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.upload.dir=C:/Users/Asus/Desktop/E Commerce workspace/assets/uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB

inventory.reservation.ttl.minutes = 15