package com.ecom.order.model;

public enum OrderEventType {
    ORDER_CREATED,
    CONFIRMATION_STARTED,
    INVENTORY_RESERVED,
    INVENTORY_RESERVATION_FAILED,
    INVENTORY_RELEASED,
    PAYMENT_INITIATED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    ORDER_CANCELLED,
    ORDER_COMPLETED,
}