server:
  port: 8761

spring:
  application:
    name: eureka-server

  config:
    import: optional:file:eureka-server/.env[.properties]

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

  server:
    eviction-interval-timer-in-ms: 10000
    enable-self-preservation: false

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO